invitados = ['José', 'Mario', 'Euclides', 'Rosa Marina']
print(f'Hola {invitados[0].title()} te invito a cenar')
print(f'Hola {invitados[1].title()} te invito a cenar')
print(f'Hola {invitados[2].title()} te invito a cenar')
print(f'Hola {invitados[-1].title()} te invito a cenar')
print("-----------------------------------------------")
print(f"{invitados[1].title()} no puede asistir")
print("-----------------------------------------------")
invitados[1] = 'Regina'
print(f'Hola {invitados[0].title()} te invito a cenar')
print(f'Hola {invitados[1].title()} te invito a cenar')
print(f'Hola {invitados[2].title()} te invito a cenar')
print(f'Hola {invitados[-1].title()} te invito a cenar')
print("-----------------------------------------------")
print("Hemos encontrado una mesa de comedor más grande")
invitados.insert(0, 'Mario')
invitados.insert(3, 'Jorge')
invitados.insert(-1, 'Marina')
print("-----------------------------------------------")
print("Bienvenida a los nuevos invitados")
print(f'Hola {invitados[0].title()} te invito a cenar')
print(f'Hola {invitados[1].title()} te invito a cenar')
print(f'Hola {invitados[2].title()} te invito a cenar')
print(f'Hola {invitados[3].title()} te invito a cenar')
print(f'Hola {invitados[4].title()} te invito a cenar')
print(f'Hola {invitados[5].title()} te invito a cenar')
print(f'Hola {invitados[6].title()} te invito a cenar')
print("-----------------------------------------------")
print("La mesa no llegará a tiempo para la cena y solo puedo invitar a dos personas a cenar")
invitado = invitados.pop()
print(f"Lo siento {invitado.title()}, no te puedo invitar a cenar")
invitado = invitados.pop()
print(f"Lo siento {invitado.title()}, no te puedo invitar a cenar")
invitado = invitados.pop()
print(f"Lo siento {invitado.title()}, no te puedo invitar a cenar")
invitado = invitados.pop()
print(f"Lo siento {invitado.title()}, no te puedo invitar a cenar")
invitado = invitados.pop()
print(f"Lo siento {invitado.title()}, no te puedo invitar a cenar")
print("-----------------------------------------------")
print(f"{invitados[0].title()}, aún estás invitado")
print(f"{invitados[1].title()}, aún estás invitado")
print("-----------------------------------------------")
del invitados[0]
del invitados[0]
print(invitados)
